import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Reza Fazriansyah | Portofolio',
    description: 'Generated by Reza Fazriansyah',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className='bg-[#000000] font-anonymousPro'>
                <Navbar />
                {children}
            </body>
        </html>
    );
}
